export const ROOT = '/';
export const HOME = '/home';
export const LOGIN = '/login';
export const LOGOUT = '/logout';
export const HABITS = '/habits';
export const CREATE = HABITS + '/create';
export const FULFILMENTS = HABITS + '/fulfill';
export const REGISTER = '/register';
export const PROFILE = '/profile';
